// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFE-DA1aWMRHDpBc6EZzYz5BDOB_w5hdo',
    appId: '1:539159546141:web:6ca655f2a7e430546979f4',
    messagingSenderId: '539159546141',
    projectId: 'bill-splitter-ed27b',
    authDomain: 'bill-splitter-ed27b.firebaseapp.com',
    storageBucket: 'bill-splitter-ed27b.firebasestorage.app',
    measurementId: 'G-LYGKZL26QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa750GYpZnN-Snpb9vWLsV9gti_3ZbWJQ',
    appId: '1:539159546141:android:e2824bdcc006b2236979f4',
    messagingSenderId: '539159546141',
    projectId: 'bill-splitter-ed27b',
    storageBucket: 'bill-splitter-ed27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPIpSg9XuL_BKMjo0t4OavlpGCt4-JLSk',
    appId: '1:539159546141:ios:a1b03b7413c262096979f4',
    messagingSenderId: '539159546141',
    projectId: 'bill-splitter-ed27b',
    storageBucket: 'bill-splitter-ed27b.firebasestorage.app',
    iosBundleId: 'com.example.billSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPIpSg9XuL_BKMjo0t4OavlpGCt4-JLSk',
    appId: '1:539159546141:ios:a1b03b7413c262096979f4',
    messagingSenderId: '539159546141',
    projectId: 'bill-splitter-ed27b',
    storageBucket: 'bill-splitter-ed27b.firebasestorage.app',
    iosBundleId: 'com.example.billSplitter',
  );
}
